using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Maid.AuthPanel;

[GenerateTypedNameReferences]
public sealed partial class AuthPanelMenu : FancyWindow
{
    private Action<BaseButton.ButtonEventArgs>? _redButtonHandler;

    public void OnRedButtonPressed(Action<BaseButton.ButtonEventArgs> func)
    {
        if (_redButtonHandler != null)
            RedButton.OnPressed -= _redButtonHandler;

        _redButtonHandler = func;
        RedButton.OnPressed += _redButtonHandler;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && _redButtonHandler != null)
        {
            RedButton.OnPressed -= _redButtonHandler;
            _redButtonHandler = null;
        }
        base.Dispose(disposing);
    }

    public void SetCount(Label label, int conf, int maxconf)
    {
        label.Visible = conf != 0;
        label.Text = conf + "/" + maxconf;
    }

    public void SetRedCount(int conf, int maxconf)
    {
        SetCount(RedCount, conf, maxconf);
        RedButton.Disabled = conf >= maxconf;
    }

    public string GetReason()
    {
        return Reason.Text;
    }

    public void SetReason(string reason)
    {
        Reason.Text = reason;
        Reason.Editable = false;
    }

    public void UnlockReason()
    {
        Reason.Editable = true;
    }
}
