- type: soundCollection
  id: HateEngine
  files:
    - /Audio/_Maid/Misc/Train/thom_1.ogg
    - /Audio/_Maid/Misc/Train/thom_2.ogg
    - /Audio/_Maid/Misc/Train/thom_3.ogg
    - /Audio/_Maid/Misc/Train/thom_4.ogg
    - /Audio/_Maid/Misc/Train/thom_5.ogg
    - /Audio/_Maid/Misc/Train/thom_6.ogg
    - /Audio/_Maid/Misc/Train/thom_7.ogg
    - /Audio/_Maid/Misc/Train/thom_8.ogg
